Update set-publish-gh-pages script and publish.yml workflow

diff --git a/set-publish-gh-pages b/set-publish-gh-pages
--- a/set-publish-gh-pages
+++ b/set-publish-gh-pages
@@ -4,18 +4,36 @@
 #
 # ONLY RUN ONCE TO SET UP GITHUB PAGES
 #
-# Preparation ---------------------------------------------------------------
+# Local repo ----------------------------------------------------------------
 # 1. Make sure all your changes are committed
 #
-# Script ---------------------------------------------------------------------
+# From the terminal:
 # 2. Run this script to publish your website to GitHub Pages on the `gh-pages` branch.
+# $ ./set-publish-gh-pages
 #
 # GitHub repo ---------------------------------------------------------------
-# 3. Set source branch to `gh-pages` and folder to `/ (root)` in the settings of your repository.
+# 3. Open settings, Pages.
+# 4. Set source branch to `gh-pages` and folder to `/ (root)` in the settings of your repository.
 #
+# Local repo ----------------------------------------------------------------
+# 5. Make sure to commit and push the .github/workflows/publish.yml file to the main branch.
 ###############################################################################
 
 # RUN SCRIPT
+
+# Amend the git credential.helper to store the GitHub token
+# Try to run a command with sudo and capture its exit status
+sudo -n true 2>/dev/null
+SUDO_STATUS=$?
+
+if [ $SUDO_STATUS -eq 0 ]; then
+    echo "User has sudo privileges, updating credential.helper"
+    sudo git config --system --unset credential.helper
+    git config --global --unset credential.helper
+    git config --global credential.helper 'cache --timeout=10000000'
+else
+    echo "User does not have sudo privileges. credential.helper not changed."
+fi
 
 # Create a new branch named `gh-pages`
 git checkout --orphan gh-pages
@@ -54,7 +72,7 @@ jobs:
         with:
           target: gh-pages
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
 
 EOL
 
